name: image
on:
  push:
    branches:
      - 'main'
      - 'release*'

permissions:
  contents: read
  packages: write
  id-token: write 

jobs:
  push-init-kyverno:
    uses: kyverno/kyverno/.github/workflows/reuse.yaml@main
    with:
      publish_command: ko-build-initContainer
      image_name: kyvernopre
      tag: image
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  push-kyverno:
    uses: kyverno/kyverno/.github/workflows/reuse.yaml@main
    with:
      publish_command: ko-build-kyverno
      image_name: kyverno
      tag: image
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  push-kyverno-cli:
    uses: kyverno/kyverno/.github/workflows/reuse.yaml@main
    with:
      publish_command: ko-build-cli
      image_name: kyverno-cli
      tag: image
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}
